### ISSUE TITLE
REQUEST: Option to dump the tabs?

### ISSUE THREAD

**Issue by GambetTV** [cs96and/FoundryVTT-damage-log#1]
LOVE this module. Been hoping someone would make something like this for a long time now. The only thing is, I'm not a big fan of spreading everything out to multiple chat tabs, and would prefer it all to just be in one chat room. Is there any chance you could add a setting to turn off the chat room tabs?

**Comment by cs96and** [comment]
Possibly.  I'll take a look into it.

**Comment by cs96and** [comment]
v1.0.1 now has a setting to disable the extra tab.
