### ISSUE TITLE
Damage not being sent to separate chat tab

### ISSUE THREAD

**Issue by AlexJPF** [cs96and/FoundryVTT-damage-log#10]
Foundry VTT v0.8.9

The radio button "Use separate damage log tab" does not appear to be working. Damage log output is still being sent to regular chat tab.

![Screen Shot 2021-09-18 at 9 30 17 PM](https://user-images.githubusercontent.com/45736019/133913474-1866c0a3-9552-46ae-b937-c62f29b38c5e.png)

![Screen Shot 2021-09-18 at 9 30 30 PM](https://user-images.githubusercontent.com/45736019/133913476-e4ee22f0-418f-40e8-81ba-960df95f6f59.png)

**Comment by cs96and** [comment]
Which version of Damage log?

Do you have any other modules enabled?  If so, can you try with just damage log enabled?

**Comment by cs96and** [comment]
Also I notice that the message is not green or red, so the CSS is not being proper applied here.

Are there any errors in the console?

**Comment by rmasoni** [comment]
I had the same thing while testing it after I first installed the module, but when I used it in the actual session, it worked correctly. Not really sure what caused it to appear on the main chat. I'll report back if I find a way to reproduce the issue.

**Comment by AlexJPF** [comment]
I'm not sure what I was on, whatever latest was when I opened the issue. I just updated to 1.5.2 and it's still present. 

I'm afraid of what happens to my world and settings if I disable all the modules.

**Comment by rmasoni** [comment]
That might be it. I had the issue when I was the only one logged in.

**Comment by cs96and** [comment]
When a message gets sent to the wrong tab, are there any errors in the console?

**Comment by rmasoni** [comment]
I haven't been able to reproduce this yet. I'll try again later and keep an eye on the console.

**Comment by AlexJPF** [comment]
I'll check console this evening, haven't been in their the last few days.

**Comment by cs96and** [comment]
Our of interest, which system are you using?

**Comment by rmasoni** [comment]
It's D&D 5e for me.

**Comment by meldogs** [comment]
I ran into this error too. Foundry 0.8.9, PF2E 2.14.1.8153, and Damage Log 1.5.2
![Damage Log Error](https://user-images.githubusercontent.com/71352952/135276077-4efc619f-0064-41d4-821e-5d06ab38464a.PNG)

![Chat Log](https://user-images.githubusercontent.com/71352952/135276144-3c6e0582-72a7-440c-a23d-e275d0fb251e.PNG)
.

**Comment by cs96and** [comment]
Out of interest what browser are you using?  I have a feeling I may be using some feature of JavsScript that is not supported in all browsers

**Comment by meldogs** [comment]
Chrome Version 94.0.4606.61 (Official Build) (64-bit)
I was just going to post that when I logged out and then back into the world everything looked normal. I applied the damage from the previous attack again and it worked properly.
![Chat Log 2](https://user-images.githubusercontent.com/71352952/135278535-9a622b91-f6cc-4b46-aee1-795b1ab8ad8c.PNG)
![Damage Log 2](https://user-images.githubusercontent.com/71352952/135278596-f5c5da79-a197-402a-92e9-c00024f39515.PNG)

**Comment by meldogs** [comment]
I found out one more thing. The error comes back when you clear the chat log. I deleted everything in the chat log and made the attack/applied the damage and the error returned. I don't know if that is useful information but I thought I would let you know just in case. Also, there are actually four errors that get created. I only included one in the first capture because they looked to be the same but this one has all four in case that is important. Love the mod and thanks for your help.
![Damage Log Error 2](https://user-images.githubusercontent.com/71352952/135284325-b7ee84fd-950a-41b4-8ad9-f8eb4e809b15.PNG)

**Comment by AlexJPF** [comment]
Appreciate others stepping in as I haven't had time to troubleshoot. Thanks!

@meldogs - what modules are you using to get that output? Feel free to message me on discord (BronzeToad#2551) to keep this chat clear for @cs96and.

**Comment by cs96and** [comment]
> I found out one more thing. The error comes back when you clear the chat log. I deleted everything in the chat log and made the attack/applied the damage and the error returned. I don't know if that is useful information but I thought I would let you know just in case. Also, there are actually four errors that get created. I only included one in the first capture because they looked to be the same but this one has all four in case that is important. Love the mod and thanks for your help. ![Damage Log Error 2](https://user-images.githubusercontent.com/71352952/135284325-b7ee84fd-950a-41b4-8ad9-f8eb4e809b15.PNG)

How are you applying the damage?  Are you just modifying the HP directly in the token?  Or does PF2 have apply damage buttons that you are using?

**Comment by meldogs** [comment]
> How are you applying the damage? Are you just modifying the HP directly in the token? Or does PF2 have apply damage buttons that you are using?

PF2E has a button for applying damage / healing.
![Apply Damage](https://user-images.githubusercontent.com/71352952/135286851-20e9e3d8-8ba2-4ed8-bc34-1fc5315d0b66.PNG)
.

**Comment by meldogs** [comment]
FYI - I tried modifying the HP directly from the token just now and that works properly. Sorry, I should have tried that before sending the last message.

**Comment by cs96and** [comment]
3ed8fffc4e6c102c369a51ab1ea82ae6cd2dc37e
2c55acc44f665c4f93523f13b2b17a5f1d0a77db

**Comment by cs96and** [comment]
This should now be fixed in 1.5.3

**Comment by rmasoni** [comment]
Just want to let you know that I on DnD5e did not use the apply damage buttons. I applied the damage directly.

**Comment by cs96and** [comment]
> Just want to let you know that I on DnD5e did not use the apply damage buttons. I applied the damage directly.

Can you check that 1.5.3 fixes the issue for you please?

**Comment by AlexJPF** [comment]
Confirmed resolved with 1.5.3
