### ISSUE TITLE
Hide "healing" from appearing on the damage log

### ISSUE THREAD

**Issue by VaethConner** [cs96and/FoundryVTT-damage-log#12]
I don't want my players to see a boss "healing", but I do want them to see it taking damage, so having an option to disable healing being shown would be helpful!

**Comment by cs96and** [comment]
Interesting idea.  Do you show your players the full damage log, or the limited one?  If I added this feature, it would probably only apply to the limited version.

**Comment by VaethConner** [comment]
I make minimum actor permission to limited (so they see other players) and have show limited damage info to players checked.
![image](https://user-images.githubusercontent.com/47077661/143319876-8a50e7cb-c51e-4851-992f-e2efe2d0f04a.png)

**Comment by cs96and** [comment]
Ok, so if I only implement this on the "Show limited damage info to players", then they would still be able to see each other healing, but not the monsters/NPCs.  I think that is what you want?

**Comment by VaethConner** [comment]
Yes, exactly, that would help immensely.

**Comment by cs96and** [comment]
45bd0f998a15f23f495614f89c096d76162a68bb

**Comment by cs96and** [comment]
Fixed in v1.6.0.
