### ISSUE TITLE
ReferenceError: tab is not defined

### ISSUE THREAD

**Issue by PhluXx1** [cs96and/FoundryVTT-damage-log#13]
I'm receiving the error "ReferenceError: tab is not defined" when trying to clear the chat log. 

I've disabled my modules and identified it as an issue in relation with the [Tabbed Chatlog](https://foundryvtt.com/packages/tabbed-chatlog) module. When Damage Log and Tabbed Chatlog are active it's not possible to clear the entire chat log, it is possible to delete each entry individually however. 

Thanks for the help and all of the great work you do for the Foundry community (much respect for the pull request you did for TorchLight to get it to 0.8).

![image](https://user-images.githubusercontent.com/72770484/147136705-e208393f-8956-45a8-bed7-7c2cfcfec08e.png)

**Comment by cs96and** [comment]
1927ce8393d0fca32bbf09e72fff6f3e8bd94f78

**Comment by cs96and** [comment]
Fixed in v1.6.2
