### ISSUE TITLE
BUG: Temporary HP does not show up in the Damage Log

### ISSUE THREAD

**Issue by GambetTV** [cs96and/FoundryVTT-damage-log#14]
If a player has 20 HP and 5 Temp HP and I deal 6 damage to them, the damage log will only show that the character has lost 1 HP. It will not mention the Temp HP at all. If I tell it to undo the damage, it will only apply 1 HP of healing to them, and won't revert the Temp HP at all.

**Comment by cs96and** [comment]
Which system are you using?

**Comment by GambetTV** [comment]
DnD5e on Foundry v9

**Comment by cs96and** [comment]
Fixed in 1.6.3
