### ISSUE TITLE
Error: Mod Conflict

### ISSUE THREAD

**Issue by Crowguard** [cs96and/FoundryVTT-damage-log#17]
[W] libWrapper: Potential conflict detected between module Damage Log and [module Actually Private Rolls, module Monk's Little Details].
Module damage-log did not chain the wrapper for 'ChatLog.prototype.notify'. libWrapper-notifications.js:89:5

https://gitlab.com/koboldworks/agnostic/private-rolls
https://github.com/ironmonk88/monks-little-details

I'll sign up for GitLab & open a ticket there too. Not really sure who has the issue here.

**Comment by cs96and** [comment]
c62d29a44b401a5b1651f97ec625ed2f31229577

**Comment by cs96and** [comment]
Fixed in 1.6.5
