### ISSUE TITLE
[System Request] SWADE

### ISSUE THREAD

**Issue by brunocalado** [cs96and/FoundryVTT-damage-log#18]
Hi. Great module!

Can you make it work for SWADE?

Wounds + Fatigue + Benes

Tks

**Comment by cs96and** [comment]
53f4599934fb96596b57e91b5a5b651bdc6afde1

**Comment by cs96and** [comment]
This will be part of the upcoming 1.8.0 release.

**Comment by brunocalado** [comment]
thank you

**Comment by cs96and** [comment]
Now available in v1.8.0
