### ISSUE TITLE
Feature Request: Suppress PF2e system damage notifications

### ISSUE THREAD

**Issue by esheyw** [cs96and/FoundryVTT-damage-log#19]
I opened an issue with the system for this a while ago (https://github.com/foundryvtt/pf2e/issues/2196) but it doesn't seem like it's getting in any time soon, so I figured I'd try asking from the other direction. With this module these notifications become redundant; if the module could (optionally?) turn them off, that'd be excellent.

**Comment by cs96and** [comment]
It might be possible to hide then with some CSS magic.  I'll take a look.

**Comment by cs96and** [comment]
Unfortunately these messages are not tagged with a unique combination of classes, so they cannot be hidden with CSS.
