### ISSUE TITLE
"Show limited info to players" option showing too much info

### ISSUE THREAD

**Issue by Tridus** [cs96and/FoundryVTT-damage-log#21]
Hi. When I use the option to "Show limited info to players" in PF2e, I'm getting this:

![image](https://user-images.githubusercontent.com/912582/178996524-6760d685-f4d3-4262-8725-5fb2f0aeff88.png)

The first part is correct as the player owns that token. The second part is showing the actual HP of the token rather than just the change, which isn't what I expect or what I saw in past versions of the mod.

This originally started as an issue with the PF2e Dorako UI ( dorako/pf2e-dorako-ui#64 ), but in the newest version of Damage Log it's happening all the time, even without any UI enabled. I uninstalled/reinstalled Damage Log and cleared caches and checked it again, so I'm confident it's not because of any changes suggested on that ticket.

Thanks.

**Comment by cs96and** [comment]
Yeah this doesn't look right.  I'll take a look

**Comment by MrVauxs** [comment]
Please see https://github.com/Dorako/pf2e-dorako-ui/issues/64

**Comment by cs96and** [comment]
de8ed9ead03adc64bc2b0f401f7ed50d0b155a38

**Comment by cs96and** [comment]
Fixed in v1.8.2
