### ISSUE TITLE
[Feature Request] Allow for styling of damage log tabs

### ISSUE THREAD

**Issue by kiligir** [cs96and/FoundryVTT-damage-log#25]
Wonderful mod! I'm using some other mods that change the default color of the interface, and think it'd be great if I could match the shadow and border colors with a color picker or hex field in the options for this mod. I can do it with custom CSS, but built-in is obviously better!

**Comment by cs96and** [comment]
What mod are you using to change the colours?

**Comment by SirMotte** [comment]
> 

Possibly things like Ernie's Modern UI and like he mentioned the Custom CSS module. Both very powerful tools.

**Comment by cs96and** [comment]
I think this actually requires a fix to Ernie's Modern UI, so that it correctly styles inactive tabs.

**Comment by cs96and** [comment]
This is now fixed in the latest version of Ernie's Modern UI
