### ISSUE TITLE
Incompatibility with DF Chat Enhancements chat merge

### ISSUE THREAD

**Issue by Talutha** [cs96and/FoundryVTT-damage-log#28]
When using this module with DF Chat Enhancements, the messages don't merge as expected until a client reload. I believe this worked before v10 but does not anymore. If I disable use separate damage tab, the behavior is as expected with the messages merging correctly. I'm not sure if this is something you want to handle and I only bring it up because it seems like you've specifically fixed it in the past. Thank you for any help you can offer :).

I have tested this with the Pathfinder 2e system with only DFCE, it's dependencies and Damage Log enabled as a GM.

**Comment by cs96and** [comment]
Can you provide a screenshot of the problem please?

**Comment by Talutha** [comment]
Sure thing!

![chrome_qGcPc1TgKI](https://user-images.githubusercontent.com/11354522/202804805-c2210d75-4c28-4ab4-8987-ca267b1c2e60.png)

This is styled with Dorako's PF2 UI but the behavior is the same without it. The top strike card is combined with the damage card as expected. The bottom two cards are not combined. On a reload of the page, the bottom two cards will be combined as expected.

Here are the same cards AFTER a reload:

![chrome_ZEYheOxHGI](https://user-images.githubusercontent.com/11354522/202805287-7b35ce4b-48d6-4e0b-b316-5833352fb431.png)

Disabling Damage Log or turning off the damage tab resolves the issue.

**Comment by cs96and** [comment]
This needs a change in DF Chat Enhancements.  I know what needs to be fixed, so I'll raise an issue on that module.
