### ISSUE TITLE
[Issue] Console Error Message

### ISSUE THREAD

**Issue by SirMotte** [cs96and/FoundryVTT-damage-log#29]
Thank you for this wonderful Module.

I do get this error message very frequently in the console log and was wondering if you know what could be going wrong.
![grafik](https://user-images.githubusercontent.com/82598692/205213584-46f28d26-c6f2-469d-a5bc-a40c94769a35.png)

I have not tested this with a clean world yet, I will do so as soon as possible, maybe you're able to pinpoint the issue until then.
![grafik](https://user-images.githubusercontent.com/82598692/205213763-70d387fd-8383-42dc-b04b-a72c056c5c85.png)

**Comment by cs96and** [comment]
I can't re-create this.  Can you try with no other modules enabled please?

**Comment by SirMotte** [comment]
Okay after hours of testing I wasn't able to recreate the issue as well. After deactivating all modules (within the world this issue happened in) and working my way through them, the error never happened again. I will close this as a one time issue that happened during module testing that day. In case I stumble across it again I'll investigate further. Sorry for the unwarranted report.

Again, thanks for this neat module, haven't used it in action yet, but I'm already sure it will make my DM life so much easier.

**Comment by cs96and** [comment]
I saw this myself today, but it disappeared after refreshing the page.  I'll keep an eye out for it happening again

**Comment by cs96and** [comment]
Found and fixed in v1.9.1
