### ISSUE TITLE
Impossible to install via manifest

### ISSUE THREAD

**Issue by apoapostolov** [cs96and/FoundryVTT-damage-log#3]
![image](https://user-images.githubusercontent.com/4083812/126370221-92620d50-195f-48b8-a91f-57c7fe3e75f5.png)

**Comment by apoapostolov** [comment]
Also zip folder lacks main folder with the mod name id.

**Comment by cs96and** [comment]
You cannot install the module using the manifest from the repository.  You must use the manifest from the latest release, i.e...

https://github.com/cs96and/FoundryVTT-damage-log/releases/latest/download/module.json

**Comment by cs96and** [comment]
I don't think there is any requirement for the module.zip to contain a top level folder.  I can see that some modules do have it (e.g. DAE), but some don't (e.g. Better Rolls).

Foundry correctly installs the zip into a correctly named directory, regardless of whether that top level folder exists or not.
