### ISSUE TITLE
[Feature Request] Compatability with Hide GM Rolls and Quick Reveal

### ISSUE THREAD

**Issue by SirMotte** [cs96and/FoundryVTT-damage-log#30]
Mentioned Modules:
[Hide GM Rolls](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls)
[Quick Reveal](https://github.com/teroparvinen/foundry-quick-reveal)

I'd like to request to add compatibility for these two modules. The first allows me to have truly private GM Rolls, without a card spoiling to my players that I rolled something. 
The second module makes revealing the cards easy by by simply hitting a shortcut. This is super fast and super efficient and has made my GMing a lot easier, as I prefer to have most of what's going on behind the scenes my matter only.

Unfortunately if the reveal damage log to players is ticked, the log messages can't be hidden and subsequently revealed to the players, but show up on the client by default.

Therefore I'd like to request compatibility for Hidden GM Rolls and, if necessary code wise, for Quick Revel as well.
I can totally understand if you don't want to jump into the rabbit hole of adding support for other modules, or if compatibility must be added by said modules themselves so feel free to dismiss this request. :)

**Comment by cs96and** [comment]
I'm not sure this is possible.  Rolling damage and applying damage are two completely separate things.  There's no way for Damage Log to know the the damage that has been applied to token is the result of a hidden roll or not.

**Comment by SirMotte** [comment]
> I'm not sure this is possible. Rolling damage and applying damage are two completely separate things. There's no way for Damage Log to know the the damage that has been applied to token is the result of a hidden roll or not.

I think the module "simply" makes all GM private rolls hidden by default and suppresses a card to show to the client. I'll ask the Author as well for good measure, maybe he can provide more insight.
As I don't understand Java Script very well, I can't be of any help in answering this.

**Comment by SirMotte** [comment]
> I presume you're using MidiQOL to roll and apply damage in one go?

No, I do not, but I'm using [Ready Set Roll](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e) which also does quick rolls.

**Comment by cs96and** [comment]
OK, but ready set roll does not automatically apply the damage, so I'm not sure how [Hide GM Rolls](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls) has anything to do with applying damage,

Are you just saying that if you click the apply damage button in a Ready Set Roll card, and that card is currently private, then you don't want the damage log shown to players?

Then, if the RSR card is revealed, then show the damage log?

**Comment by SirMotte** [comment]
> OK, but ready set roll does not automatically apply the damage, so I'm not sure how [Hide GM Rolls](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls) has anything to do with applying damage,
> 
> Are you just saying that if you click the apply damage button in a Ready Set Roll card, and that card is currently private, then you don't want the damage log shown to players?
> 
> Then, if the RSR card is revealed, then show the damage log?

I made a video showcasing what I'm talking about. It got pretty long, I'm sorry. I'm not very used to talk English freely, so pardon any hick-ups there:

https://youtu.be/F8VMw6fOids

Thank you for your time :)

**Comment by SirMotte** [comment]
Thank you for the update, this works for me for now. You may close the issue if you think you won't probe any further with this :).

**Comment by cs96and** [comment]
e272ef6d56726910d9268abde8277f2d94bdb954

**Comment by cs96and** [comment]
Sorry meant to update this issue earlier and then forgot.  Yes this is partially fixed in v1.9.0 by fixing the making private/public of damage Log entries.  If you do make an entry private or public, then a Reset Visibility option also appears which sets the visibility back to the default (usually GM and one player).

I'll leave this open for now, as I do intend to take a look at making it compatible with Ready Set Roll's visibility.  Not sure if that is possible or not yet though.

**Comment by SirMotte** [comment]
I'm not sure if ready set roll poses a problem or incompatibility. There's more likely an issue with "Hide GM Rolls". Generating damage log entries with Ready set roll works just fine.

**Comment by cs96and** [comment]
What I mean is if you click one of the apply damage buttons from a hidden RSR card, then the damage log entry can be hidden.

**Comment by cs96and** [comment]
I'm going to close this.  I am no longer planning to add the extra RSR funtionality.
