### ISSUE TITLE
[Feature Request] PF2e IWR tooltip

### ISSUE THREAD

**Issue by roguedevjake** [cs96and/FoundryVTT-damage-log#31]
Pathfinder 2e has just introduced immunity, weakness and resistance automation and one of the nice elements they introduced was to have an info icon that when hovered provides tooltip information on the damage resisted, ignored or added.

It would be great if damage log included this tooltip for PF2e.

[Imgr link to what it looks like](https://imgur.com/a/jOTWrYS)

**Comment by cs96and** [comment]
Unfortunately Damage Log only knows the end number that a token got damaged by.  It does not know the original damage that got reduced, or why.  It probably possible to do it, but sounds like a lot of work and extra module bloat that I do not want to add.
