### ISSUE TITLE
This looks really cool, any chance you can implement this for GURPS

### ISSUE THREAD

**Issue by TheFabulousIronChef** [cs96and/FoundryVTT-damage-log#32]
Not sure how difficult or easy this would be, but I'm imagining as long as you know the relevant attributes used in the GURPS Game Aid, it's probably not that hard.

**Comment by cs96and** [comment]
2781435174e5441e61d702c5a2b4c861f27a9515

**Comment by cs96and** [comment]
Now available in v1.10.0
