### ISSUE TITLE
[Feature Request] Customizable Chat Tabs compatible support

### ISSUE THREAD

**Issue by kju8** [cs96and/FoundryVTT-damage-log#43]
The Tabbed Chatlog is not maintained and has been taken over as [Customizable Chat Tabs](https://github.com/mclemente/fvtt-chat-tabs), but Customizable Chat Tabs is not compatible now.
Can you support compatibility to this module?

**Comment by cs96and** [comment]
Thanks, wasn't aware that Tabbed Chatlog was deprecated.

**Comment by cs96and** [comment]
[Customizable Chat Tabs](https://github.com/mclemente/fvtt-chat-tabs) support now available in v1.19.0
