### ISSUE TITLE
Issue installing to foundry

### ISSUE THREAD

**Issue by tobjv** [cs96and/FoundryVTT-damage-log#44]
Foundry Version 11 Build 315.

Game system: Pathfinder2e 5.13.2

Went and updated my game system and modules. All but Damage Log worked. It spits out the errors `Metadata validation failed for module "damage-log": The file "scripts/util.js" included by module damage-log does not exist`

And `setup.js:5304 Error: Cannot read properties of null (reading 'protected')`

![Screenshot_1](https://github.com/cs96and/FoundryVTT-damage-log/assets/13283561/5b377c7f-edd7-47bd-8351-11428b590bad)

**Comment by cs96and** [comment]
Should be fixed in 1.19.1
