### ISSUE TITLE
Issues with hiding max HP from players

### ISSUE THREAD

**Issue by ChobitsCrazy** [cs96and/FoundryVTT-damage-log#47]
Testing on:
Foundry: v11.315
D&D: 3.1.2
Damage Log: 1.21.0
-No conflicting modules
Settings:
![image](https://github.com/cs96and/FoundryVTT-damage-log/assets/21301107/c2b2d713-6c5c-4d5d-838d-83828646d44b)

This is the player view result:
![image](https://github.com/cs96and/FoundryVTT-damage-log/assets/21301107/498d7229-4581-46fb-8eba-b330aa07ae13)

Expectation:
To not show the maximum/current HP for the creature.

**Comment by ChobitsCrazy** [comment]
Nevermind I determined how this interacts with the "Minimum actor permission" setting.
However may want to make a note somewhere on the "Show limited damage..." setting that this is overridden by the "Minimum actor permission" setting.

**Comment by cs96and** [comment]
It's not supposed to look like that.  With dnd5e v3, it should look like this...
![image](https://github.com/cs96and/FoundryVTT-damage-log/assets/898086/5dd5dc40-07eb-4f70-95d1-d8e2d636b40b)

Have you tried disabling all other modules?  Do you have some other module enabled that adds portraits to messages (e.g. [Simply Portraits](https://foundryvtt.com/packages/simply-portraits/) or [Chat Portrait](https://foundryvtt.com/packages/chat-portrait)).  Note that portrait providing modules are no longer required with dnd5e v3 as the system now takes care of adding the portraits.

**Comment by ChobitsCrazy** [comment]
Yes the only modules enabled is this mod, the screenshots are from my test environment where I run the bare minimum. I do not have either of those mods installed.

**Comment by cs96and** [comment]
I'm still not seeing this issue.  Both the the DM view and player view look fine to me.  Can you please double check if you have *any* other modules enabled (apart from libWrapper)?

**Comment by ChobitsCrazy** [comment]
Okay I tested on a brand new world and didn't have the issue so I circled back to my main world and double checked. Turns out for the first time ever Module Management+ is conflicting with something (a module I normally exclude since it does so little).

**Comment by cs96and** [comment]
Thanks for checking again.  As Module Management+ looks deprecated, I will close this issue.

**Comment by ChobitsCrazy** [comment]
> Thanks for checking again. As Module Management+ looks deprecated, I will close this issue.

Where does it say that? Works just fine for me?
It's also included in the MIDI-Verse and verified working for v12 and DnD3.2

**Comment by cs96and** [comment]
ModuleManagement+ has not had any commits for over a year, and no issues have been fixed in that time either, so it looks abandoned.
https://github.com/mouse0270/module-credits
