### ISSUE TITLE
[Issue] Damage Log empty

### ISSUE THREAD

**Issue by Damuth1977** [cs96and/FoundryVTT-damage-log#49]
Foundry v11.315
PF1e v10.4

Damage log remains empty when applying damage or healing.  Tested with just damage log & libwrapper activated.
Added/removed health through chatcards and manually, to no effect.

[Edit] no errors in console

**Comment by vasseaude** [comment]
Same issue after updating to PF1e v10.4 - running on The Forge

**Comment by cs96and** [comment]
5053fad18a1ebb387590d8039537e9a9a148ccd5

**Comment by cs96and** [comment]
5053fad18a1ebb387590d8039537e9a9a148ccd5

**Comment by cs96and** [comment]
5053fad18a1ebb387590d8039537e9a9a148ccd5

**Comment by cs96and** [comment]
Now fixed in v1.21.1
