### ISSUE TITLE
Jump to Bottom button doesn't work when using Damage Log

### ISSUE THREAD

**Issue by heyngra** [cs96and/FoundryVTT-damage-log#51]
Foundry v12 build 331
D&D5e 3.3.1
Damage Log 1.21.1

### Reproduction steps.
1. Disable `Show limited damage info to players` and `Allow players to view the damage log`, and enable `Use separate damage log tab`.
2. Make sure that the damage log has an entry for the player character.
3. As a player, have enough messages in chat to scroll up, then scroll up.
4. Try to click `Jump to Bottom`.

Expected result: After clicking `Jump to Bottom` your chat scrolls to the bottom.
Result: `Jump to Bottom` button doesn't do anything until you remove all the damage logs affecting the player character.

Module settings:
 
![image](https://github.com/user-attachments/assets/9bf52af6-6f18-4c36-89c9-e50c51cb5dc2)

**Comment by cs96and** [comment]
f3bc39fa05011debc52f6f4c1009fdd4e19bffba

**Comment by cs96and** [comment]
Fixed in v1.22.2
