### ISSUE TITLE
[Issue] Small mistake

### ISSUE THREAD

**Issue by iwontgiveyoumyname** [cs96and/FoundryVTT-damage-log#54]
Extra comma at line 78 in damage-log.js
![issue](https://github.com/user-attachments/assets/e0a7d655-3e6c-4910-aad2-abd5995f500a)

**Comment by cs96and** [comment]
8978058

**Comment by cs96and** [comment]
Thanks.  That'll teach me for accepting a pull request via my phone!

Fixed in v1.22.1
