### ISSUE TITLE
When VTTColorSettings is enabled Damage Log uses full images instead of token

### ISSUE THREAD

**Issue by dafzor** [cs96and/FoundryVTT-damage-log#55]
When [VTTColorSettings](https://github.com/ardittristan/VTTColorSettings) module is enabled, the image used for Damage Log entries is the full image instead of the token image.

Similar to #47 

FoundryVTT: 12 Build 331
DND5e: v3.3.1
VTTColorSettings: 3.0.3
Damage Log: 1.22.1

**Comment by cs96and** [comment]
I can't recreate this with the versions you specified.  Do you have any other modules enabled?

**Comment by dafzor** [comment]
At the time i reduced the modules to just those, but as of today I also can't reproduce it any more even though the mentioned modules haven't gotten an update.

Maybe there was some interaction with another module i missed...

I'll close this for now and reopen it if I find a reproducible example

**Comment by cs96and** [comment]
As mentioned in #47, it was ModuleManagement+ that was causing that issue previously.
