### ISSUE TITLE
not working in Age of Sigmar: Soulbound 

### ISSUE THREAD

**Issue by Kasyks** [cs96and/FoundryVTT-damage-log#7]
I tried it in Age of Sigmar: Soulbound (age-of-sigmar-soulbound) ver 3.2.1 and nothing appear in damage log chat.

**Comment by cs96and** [comment]
Which version of Damage Log?

**Comment by Kasyks** [comment]
1.4.0 installed from Add-on Modules in Foundry

**Comment by cs96and** [comment]
00e1b3bd99b3fe29b3b8b581ef605141ac93dd88

**Comment by cs96and** [comment]
Fixed in 1.4.1
