### ISSUE TITLE
Bug with minimal UI

### ISSUE THREAD

**Issue by DerHerzog7** [cs96and/FoundryVTT-damage-log#8]
This seems to be a bug with Minimal UI.
When you close the sidebar then click "chat", everything pops up just fine. When you re-open the sidebar, the chat-log gets added as a duplicate. This seems to happen each time you open and close the side bar. 

See image. 

![image](https://user-images.githubusercontent.com/60498810/128657870-3dcb4a68-a78c-4681-92e6-3cd3a1ca651d.png)

**Comment by cs96and** [comment]
Thanks for the bug report.  Unfortunately I won't be able to look into this properly until next week.  In the meantime, you could try opening Data/modules/damage-log/main.js in your Foundry data directory and changing line 75 from...

`Hooks.on("renderChatLog"` ....

To

`Hooks.once("renderChatLog"` ...

I.e. change the `on` to `once`

Let me know if it works

**Comment by DerHerzog7** [comment]
It works for duplication error. Also, if the sidebar is minimised, it doesnt show at all... 
But I think it's a good temporary fix :) We can just keep the sidebar docked. 

![image](https://user-images.githubusercontent.com/60498810/128786582-82bfe46b-89fe-4a79-92b7-393aaa8d93a7.png)

**Comment by cs96and** [comment]
2ea683c2a281ef9439dae2c3b4a719c3a7514a89

**Comment by cs96and** [comment]
Fixed in v1.4.2
