### ISSUE TITLE
request - include stamina points for PF2e

### ISSUE THREAD

**Issue by ditzer252** [cs96and/FoundryVTT-damage-log#9]
Great mod!
Would you please consider tracking stamina points (an optional rule for PF2e) in the damage log.
Thanks!

**Comment by cs96and** [comment]
The longer term plan is to let you track whatever you want, by letting you enter the path to the attribute you want to track.  That could be stamina, gold, or whatever you want.  It would also make the module completely system agnostic, and let you track HP in any system.

Some work towards this went into 1.4.0, but I still need to work out how the settings interface would look.  I am also unable to do much work on the module until September.

**Comment by ProfDoof** [comment]
@cs96and, are you still planning on extending this to let you track whatever you want?

**Comment by cs96and** [comment]
4d230fdbe5ea616a07b3f1c4f3ea27657aed8c9b

**Comment by cs96and** [comment]
This is now in v1.10.0, sorry it took so long!  This just adds support for Stamina Points, it doesn't implement the generic UI to track anything you want.
